version: '3.9'

services:
  streamlit:
    image: python:3.12.5-slim
    container_name: streamlit
    working_dir: /app
    volumes:
      - "./:/app"
    ports:
      - "8501:8501"
    command: >
      sh -c "
      pip install -r requirements.txt &&
      streamlit run app.py --server.port=8501 --server.address=0.0.0.0
      "